name: Optimize resource pack
on: [push]

permissions:
@@ -28,11 +28,13 @@ jobs:
            zip_spec_conformance_level = 'disregard'
            skip_pack_icon = false

            [[file_types]]
            glob = "**/*.png"
            image_data_compression_iterations = 20
            maximum_width_and_height = 21600

            [[file_types]]
            glob = "**/*.nbt"
            nbt_compression_iterations = 25

      - name: Tag and create release
